# Created on Friday June 24 2022
#
# Authored by Jiani Zheng who wstudies at the University of Leeds as a MSc student
# 
#
# 
#
name: XAS_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5.*
  - matplotlib
  - numpy
  - pandas
  - scipy
  - lmfit


